### ISSUE TITLE
Auswahl Haltestelle

### ISSUE THREAD

**Issue by Joshuasony** [mburri/elm-swiss-station-departures#1]
Cool wäre, wenn bei der Haltestellensuche die erste Haltestelle gleich mit ENTER auswählbar (und dies auch entsprechend gekennzeichnet) wäre und wenn man mit TAB oder PFEIL NACH UTEN durch die Haltestellen-Liste durchcyclen könnte, um diese schnell und bequem per Tastatur auswählen zu können. http://vbot.ch/ hat dies so umgesetzt, ich finde das sehr benutzerfreundlich.

![grafik](https://user-images.githubusercontent.com/7139459/33653147-4a115420-da6c-11e7-8245-ecb53e3693f3.png)

**Comment by mburri** [comment]
Mit Pfeil nach unten konnte schon immer durch die Liste navigiert werden. Mit diesem commit (https://github.com/mburri/elm-swiss-station-departures/commit/0af8709b07d995463515f3b38c004c3c3526ee54) wird jetzt der aktuell markierte Eintrag noch mit " [enter]" ergänzt.

Allenfalls werde ich aber das verwendete Autocomplete-Package ersetzen/ ausbauen, da es nicht mehr wirklich weiter entwickelt wird, deshalb ist die Lösung fürs Vorauswählen des ersten Eintrages noch nicht implementiert.
Tab-navigation folgt

**Comment by Joshuasony** [comment]
Was auch cool wäre, wenn in der Vorschlagsliste jeweils der erste Eintrag bereits mit [Enter] ergänzt wird. So kann man sich den Pfeil nach unten sparen, wenn die erste vorgeschlagene Haltestelle der gesuchten Haltestelle entspricht.

**Comment by mburri** [comment]
Meiner Ansicht nach wird der erste Eintrag der Vorschläge bereits vorselektiert... allerdings gibt es noch ein Problem, dass die Liste manchmal noch umsortiert wird, nachdem ein Eintrag selektiert wurde.

**Comment by Joshuasony** [comment]
Shit sorry, das war das letzte Mal, als ich getestet habe, noch nicht so... 🙃
